# language: pt

Funcionalidade: Produto

  @a1
  Esquema do Cenario: Produto <status>
    Dado que ...
    Mas avanço ...
    Quando aceito ...
    E configuro ...
    Então deve ...

    Exemplos:
      | valor   | numero        | 
      | test | 123 | 

  @a2
  Esquema do Cenario: Pendenciado
    Dado que ...
    E busco ...
    Quando identifico ... 
    E preencho ...
    Mas aprovo ... 
    Então frontend ...

    Exemplos:
      | cpf          | produto            |
      | cpf_a2 | produto_pendente |
